web:
  build: ./app
  environment:
    NODE_ENV: development
  volumes:
    - "./app:/src/app"
  links:
    - "db:redis"
  command: nodemon -L app/bin/www
nginx:
  restart: always
  build: ./nginx/
  ports:
    - "8888:80"
  volumes_from:
    - web
  links:
    - web:web
db:
  image: redis
