web:
  build: ./app
  volumes:
    - "./app:/src/app"
  links:
    - "db:redis"
  command: nodemon -L app/bin/www

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "8080:80"
  #volumes:
  #  - /www/public
  volumes_from:
    - web
  links:
    - web:web
db:
  image: redis
